		<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js"></script>
        <script src="<?= JS_PATH ?>app.js"></script>
        <?php if (isset($data['onglet'])) : ?>
            <script>active_onglet("<?= $data['onglet'] ?>");</script>
        <?php endif; ?>

    </body>
    <footer>

    </footer>

<?php ob_end_flush(); ?>