		<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js"></script>
        <script src="<?= JS_PATH ?>app.js"></script>
        <?php if (isset($_SESSION['onglet'])) : ?>
            <script>active_onglet("<?= $_SESSION['onglet'] ?>");</script>
        <?php endif; ?>

        <?php if (isset($_SESSION['onglet_user'])) : ?>
            <script>active_onglet_user("<?= $_SESSION['onglet_user'] ?>");</script>
        <?php endif; ?>

    </body>
    <footer>

    </footer>

<?php ob_end_flush(); ?>