<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= CSS_PATH ?>style.css">
    <link rel="stylesheet" href="<?= CSS_PATH ?>fondAnime.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Lato:700|Noto+Serif" rel="stylesheet">


    <title>LoveCar</title>

</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">
    <?php    include_once 'nav.phtml';   ?>